[2024-05-04T06:30:36.141+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T06:30:36.152+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-05-04T06:26:22.281571+00:00 [queued]>
[2024-05-04T06:30:36.162+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-05-04T06:26:22.281571+00:00 [queued]>
[2024-05-04T06:30:36.162+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-04T06:30:36.185+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-05-04 06:26:22.281571+00:00
[2024-05-04T06:30:36.193+0000] {standard_task_runner.py:63} INFO - Started process 20495 to run task
[2024-05-04T06:30:36.197+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2024-05-04T06:26:22.281571+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpeayom6hx']
[2024-05-04T06:30:36.198+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask is_weather_api_ready
[2024-05-04T06:30:36.235+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2024-05-04T06:26:22.281571+00:00 [running]> on host ip-172-31-26-226.eu-north-1.compute.internal
[2024-05-04T06:30:36.314+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T06:26:22.281571+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T06:26:22.281571+00:00'
[2024-05-04T06:30:36.318+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T06:30:36.319+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-04T06:30:36.320+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Portland&APPID=5031cde3d1a8b9469fd47e998d7aef79
[2024-05-04T06:30:36.328+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-05-04T06:30:36.521+0000] {http.py:199} ERROR - HTTP error: Unauthorized
[2024-05-04T06:30:36.522+0000] {http.py:200} ERROR - {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
[2024-05-04T06:30:36.522+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T06:30:36.528+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 197, in check_response
    response.raise_for_status()
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=Portland&APPID=5031cde3d1a8b9469fd47e998d7aef79

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 187, in run
    return self.run_and_check(session, prepped_request, extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 238, in run_and_check
    self.check_response(response)
  File "/home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 201, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 401:Unauthorized
[2024-05-04T06:30:36.535+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=is_weather_api_ready, execution_date=20240504T062622, start_date=20240504T063036, end_date=20240504T063036
[2024-05-04T06:30:36.547+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task is_weather_api_ready (401:Unauthorized; 20495)
[2024-05-04T06:30:36.571+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T06:30:36.581+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/airflow_environment/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2024-05-04T06:30:36.595+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T06:30:36.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
